### ISSUE TITLE
Capability to run jobs interactively an event at a time

### ISSUE THREAD

**Issue by heather999** [SNiPER-Framework/sniper#11]
For another project using the Gaudi framework, we provided the capability to run a job one event at a time, allowing the user to run interactively. This could be done either at the command line or using an event display GUI.  This was done using:
https://gitlab.cern.ch/gaudi/Gaudi/blob/master/GaudiKernel/GaudiKernel/IAppMgrUI.h

Is there any think like that in SNiPER?

**Comment by zoujh** [comment]
In SNiPER there is a class named TaskWatchDog in SniperKernel, which can be used for interactive event processing or GUI integration.

Code example in Python:
```
# some preparation ...
task = Task("task")

# the configuration...

# instead invoking task.run(), we get a TaskWatchDog for interactive execution
snoopy = task.Snoopy()    #the TaskWatchDog instance
snoopy.config()
snoopy.initialize()

snoopy.run_once()   #process only 1 event (the next event), which can be invoked many times

snoopy.finalize()
snoopy.terminate()
```

**Comment by heather999** [comment]
Thanks, I have passed this on to the nEXO team.  I will close this issue for now.
