### ISSUE TITLE
On a FATAL error condition, how do we properly exit SNiPER?

### ISSUE THREAD

**Issue by heather999** [SNiPER-Framework/sniper#12]
When dealing with an error condition where we want the SNiPER job to fully terminate - what is the best way to do that?  If we encounter an error within an algorithm, for example - I would post a LOGFATAL.  Is that enough to trigger termination?  Or should we also go ahead and execute a sys.exit() or something else ?

**Comment by zoujh** [comment]
LOGFATAL only prints a message. However, we can terminate a SNiPER process explicitly via the interface Task::stop(). 

1. In an algorithm, we can get the Task pointer by invoking getParent(), or the TopTask pointer by invoking getRoot();
2. Task::stop() accepts an enum argument, which means:
  - Sniper::StopRun::Promptly, stop the event loop immediately;
  - Sniper::StopRun::Peacefully, continue the execution of the algorithm sequence for current event, then stop event loop before next event;
  - Sniper::StopRun::ThisEvent, stop the execution for current event, jump to the next event and continue processing the event loop;

Code example:
```
bool AnUserAlg::execute()
{
    // do some thing ....

    if ( want_to_stop_immediately ) {
        getRoot()->stop( Sniper::StopRun::Promptly );
    }
    // else .....
}
````

**Comment by heather999** [comment]
Thanks, I have passed this onto the nEXO team.  I'll go ahead and close this issue.
