### ISSUE TITLE
CMT and Py3

### ISSUE THREAD

**Issue by heather999** [SNiPER-Framework/sniper#13]
Hi,
Right now, the CMT build of `sniper` requires some updates to work with python 3.  What is the plan?  Should CMT building be deprecated in favor of using CMake?  Or should work be done to update the CMT configuration to work with python3?  It looks like SniperPolicy/cmt/fragments/install.py needs some updates to `print` and the use of `izip` to be compatible with Py3.

**Comment by samusangio** [comment]
Hi,  is there a reason for maintaining CMT at all? Are there parts of SNiPER that cannot be made to work with CMake (and Python3)?  If not, I would deprecate CMT completely.  

@vbelov42 - I'm interested in your take on this.

**Comment by zoujh** [comment]
Finally and finally, I managed to move to CMake, see #18 . I hope everything goes smoothly.

**Comment by zoujh** [comment]
I think I can close this issue now.
