### ISSUE TITLE
Property: passing huge int value from Python to C++

### ISSUE THREAD

**Issue by tangzhch** [SNiPER-Framework/sniper#16]
An int is 64 bit in python but in 32 bit in C++. For an int property when passing value from Python to C++ one could get value overflow error.
```python
>>> v = 9876543210
>>> a.property("LogLevel").set(v)

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

OverflowError: bad numeric conversion: positive overflow
```

Well the exception explains the fact. But a more user friendly message would be more useful, especially for new users. E.g. "value for int property should not excess 32bit."

**Comment by zoujh** [comment]
I don't think so. This is an "official" message of Python.
In my opinion,
- an "official" message is more helpful for users to find help on web (and also somewhere else);
- it is too hard to customize different error messages for all the data types;

**Comment by tangzhch** [comment]
> I don't think so. This is an "official" message of Python.
> In my opinion,
> 
>     * an "official" message is more helpful for users to find help on web (and also somewhere else);
> 
>     * it is too hard to customize different error messages for all the data types;

In my option the exceptions are designed to be catched, if possible. We can discuss whether the current error message are enough or not. However we can always preseve the original message, by rethrowing the very same exception.

After digging, the error is found to be from [`boost::numeric_cast`](https://www.boost.org/doc/libs/1_74_0/libs/numeric/conversion/doc/html/boost_numericconversion/improved_numeric_cast__.html). there are two exception class, `boost::numeric::positive_overflow` and `boost::numeric::negative_overflow`, will be thrown. We could easily catch them in `SniperProperty::set()` after the call of `_var()`.

We can deliver a message like "Value too large for a int (32bit unsigned)" or "Nagative value too large ..." or even "Value can not be negative for unsigned int (32bit)", which are more user-friendly. We could discuss how much information to provide, but I think as a minimum we should give a hint of the destination data type, because the user may not konw for detail of that.

**Comment by zoujh** [comment]
We can get a message with the property data type now, see #17 .
