### ISSUE TITLE
python configuration scripts and batch job submission

### ISSUE THREAD

**Issue by heather999** [SNiPER-Framework/sniper#3]
@mirguest & @zoujh 
nEXO is wondering if the python configuration scripts used to start up a SNiPER job support job submission to a batch system? I do not recall there is any facility already in the SNiPER python configuration scripts. Are there examples where the python config scripts also submit a job to batch?

**Comment by zoujh** [comment]
@heather999 
I am a little confused about your question. Batch systems, such as LSF, Slurm and HTCondor, accept any executable script as a job. In our case, we can submit an executable SNiPER configuration script directly. Do you mean a unified wrapper/command on top of users' configurations? It's difficult to provide such a wrapper that be compatible with different experiments and batch systems. However, it should be much easier to a specific experiment with a specific batch system.

**Comment by heather999** [comment]
Thanks @zoujh Agreed! I'll close this, but if other questions, come up from nEXO, I'll let you know.
