### ISSUE TITLE
Wrapping existing python code in SNiPER

### ISSUE THREAD

**Issue by heather999** [SNiPER-Framework/sniper#4]
Hi @mirguest & @zoujh 
nEXO is preparing to port some existing reconstruction code written in python so that it is callable from SNiPER.  It would be easier to just embed the python in C++ rather than rewriting the reconstruction code.  Do you have an example of a SNiPER algorithm that uses Python rather than just C++?  Do you recommend Boost::python?
Take care,
Heather

**Comment by zoujh** [comment]
Hi @heather999 
I am afraid we can not invoke a python algorithm directly in SNiPER at present. But, it is possible to implement an adapter by which we can invoke some python code. The difficulty is the data handling. It's a little complicated to transfer a C++ event object (EDM in nEXO offline) to python, or reverse.
However, if we use a simplified data model in python, it can be easier. I will try to provide such an example.
Best regards,
Jiaheng

**Comment by heather999** [comment]
Hi @zoujh,
Yes that sounds like exactly what we would need.  Some translation from a C++ event object to a data model usable in python should make it easier.  An example would be greatly appreciated!
Take care,
Heather

**Comment by zoujh** [comment]
Hi @heather999 
I add some new features on writing Python algorithms. You can see the ChangeLog file for details.
BTW, @mirguest mentioned that when the EDM ROOT dictionary is loaded, the EDM event objects can be accessed in Python. Then we can use the full functionalities of the EDM. However, we need some extra efforts to get the event object from the data buffer first.
Best regards,
Jiaheng

**Comment by heather999** [comment]
Hi @zoujh Thank you, I will take a look at it!

**Comment by heroxbd** [comment]
@heather999 Hi Heather, FYI https://docs.python.org/2/extending/embedding.html .  But I don't think embedding is the way to go. Mixing C++ and Python programs in one project makes more sense to me.
